server {
    listen 80;

    # ======================
    # ANGULAR (proxy)
    # ======================
    location / {
        proxy_pass http://web:4200;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # ======================
    # LARAVEL API
    # ======================
    location /api {
        root /var/www/public;
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        root /var/www/public;

        include fastcgi_params;
        fastcgi_pass api:9000;
        fastcgi_index index.php;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    error_log /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
}