server {
    listen 80;

    # FRONTEND (Angular)
    root /var/www/frontend;
    index index.html;

    # Servir Angular
    location / {
        try_files $uri $uri/ /index.html;
    }

    # API Laravel
    location /api {
        alias /var/www/public;
        try_files $uri $uri/ /index.php?$query_string;

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass api:9000;
            fastcgi_param SCRIPT_FILENAME /var/www/public/index.php;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }
    }

    error_log /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
}